version: "3.7"
services:
  ubuntu:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
    image: docker-sample_ubuntu
    container_name: ubuntu
    hostname: ubuntu
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true
  centos:
    build:
      context: .
      dockerfile: ./centos/Dockerfile
    image: docker-sample_centos
    container_name: centos
    hostname: centos
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true
  alpine:
    build:
      context: .
      dockerfile: ./alpine/Dockerfile
    image: docker-sample_alpine
    container_name: alpine
    hostname: alpine
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true

networks:
  default:
    external:
      name: bridge
  compose-network:
    name: compose-network
