version: "3.7"
services:
  ubuntu:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
    image: docker-sample-ubuntu
    container_name: docker-sample-ubuntu
    hostname: docker-sample-ubuntu
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true
  centos:
    build:
      context: .
      dockerfile: ./centos/Dockerfile
    image: docker-sample-centos
    container_name: docker-sample-centos
    hostname: docker-sample-centos
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true
  alpine:
    build:
      context: .
      dockerfile: ./alpine/Dockerfile
    image: docker-sample-alpine
    container_name: docker-sample-alpine
    hostname: docker-sample-alpine
    networks:
      - compose-network
    volumes:
      - .:/docker
    tty: true
    privileged: true

networks:
  default:
    external:
      name: bridge
  compose-network:
    name: compose-network
