name: centos
on: [push, pull_request]
jobs:
  centos:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker-sample-centos-test
      SERVICE_NAME: centos
    steps:
      - uses: actions/checkout@v2
      - name: docker compose test
        run: docker-compose -f $SERVICE_NAME/docker-compose.test.yml up
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Install dockle
        run: |
          VERSION=$(
          curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
          grep '"tag_name":' | \
          sed -E 's/.*"v([^"]+)".*/\1/' \
          ) && curl -L -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz \
          && tar zxvf dockle.tar.gz
      - name: Run dockle
        run: ./dockle --exit-code 1 --exit-level fatal $IMAGE_NAME
